### ISSUE TITLE
Limit what types can be turned into Foreign

### ISSUE THREAD

**Issue by chexxor** [purescript/purescript-foreign#55]
My understanding of Foreign is that a Foreign is a JS value. Not all PS types are JS types, right?

So, we should change the `toForeign` function as follows, to ensure that only base JS types are Foreign.

``` purescript
foreign import toForeign :: forall a. a -> Foreign
-- Change to
foreign import toForeignString :: String -> Foreign
foreign import toForeignNumber :: Number -> Foreign
foreign import toForeignArray :: Array Foreign -> Foreign
foreign import toForeignObject :: StrMap Foreign -> Foreign
foreign import toForeignUnsafe :: forall a. a -> Foreign
```

Is my understanding wrong?

**Comment by paf31** [comment]
> Not all PS types are JS types, right?

I guess it depends what you mean by "JS type".

If you mean values of JSON documents, or things which can easily be distinguished using `typeof`, then perhaps. But I think there is some value in allowing anything, for example `StrMap`.

**Comment by garyb** [comment]
It's also useful for cases where you want to "upcast" things in `purescript-dom`, e.g. to safely convert `Event` -> `MouseEvent` you need to `toForeign` and then `readMouseEvent`. I suppose we could provide functions to do that, but the most convenient implementation would be via `toForeign` anyway!

**Comment by chexxor** [comment]
@paf31 - I was referring to the typeclasses. Not every PS type can have an instance of IsForeign/AsForeign, such as my initial effort to define HugeNum an instance of AsForeign. I wanted to encode it as Number, but that's a lossy encoding. (https://github.com/purescript-contrib/purescript-precise/pull/4#discussion_r90776485). I suppose I could implement it as `write hugeNum = toForeign hugeNum`, but that feels so much like `unsafeCoerce` that I don't like using it. If these classes had better docs describing their intention/laws, then I would likely be more comfortable `toForeign`.

Following is an argument for removing all capabilities of turning PS data *into* Foreign type.

Previous discussion shows the intention that Foreign values are values which *come from* outside a PS app (https://github.com/purescript/purescript-foreign/issues/30#issuecomment-135789173, https://github.com/purescript/purescript-datetime/issues/36#issuecomment-229026687).

If that was the original intention, why has Foreign's scope has expanded to encoding PS values as Foreign values? I believe this is a strange aspect for Foreign to cover. A PS program must run as JS, so all PS data *is* JS data (though they might be relatively unusual JS structures). We should be able to write a proper type for anything we pass to a JS function.

Following is an example which illustrates why I think this is strange.

``` purescript
-- What should `pushState` take here \/? `forall a`? Or Foreign?
--   Or a type which better describes acceptable values?
foreign import pushState :: forall e. _ -> DocumentTitle -> URL -> History -> Eff (history :: HISTORY | e) Unit

-- Previous discussion states that `HugeNum` *isn't* Foreign.
newtype SomeRecord = SomeRecord { name :: String, amountSpent :: HugeNum }

sampleSomeRecord = SomeRecord { name: "Page1", amountSpent: fromNumber 2.50 }

main = pushState (?f sampleSomeRecord) bla bla bla
```

Why must we turn `sampleSomeRecord` to Foreign? Does it mean that `pushState` only works with valid JS values? But all PS data *is* JS data, so why can't I use a more descriptive PS type to describe this argument to pushState? If we decide that we *should* use a descriptive PS type here, then shouldn't that decision apply to *all* functions?

All examples in [purescript-foreign/examples](https://github.com/purescript/purescript-foreign/tree/master/examples) are parsing Foreign into PS types. Do you know any examples of library functions which you think are properly using Foreign as an argument?

**Comment by natefaubion** [comment]
> Following is an argument for removing all capabilities of turning PS data into Foreign type.

Generally I agree with this. I've said it elsewhere, but I think trying to force `Foreign` to support the use case of encoding/decoding is what makes it confusing. I think Foreign should be used to reflect information about arbitrary runtime values of the host (host tags, property reflection, etc). I'd even go so far as to say there should be language specific `Foreign` libraries as a lot of the functions don't make sense in any other host. All PS values can be made `Foreign` by forgetting it's type with `toForeign`, and it thus becomes an arbitrary runtime value. If an API let's you store arbitrary runtime values with no restrictions, then it makes sense to put `Foreign` in the API. This isn't necessarily retrievable on the PS side though (if you wanted to do that you might need something like `Dynamic/Typeable` in Haskell), so otherwise you'd want serialization with `Json`.

**Comment by paf31** [comment]
> I think trying to force Foreign to support the use case of encoding/decoding is what makes it confusing

If functions like `readString` and `readArray` are okay, then I should be able to use those functions to build bigger values from `Foreign` values. But now I'm describing a decoder.

**Comment by natefaubion** [comment]
I think that the functions are useful for building decoders, but I don't think it should be the mission of Foreign to provide a blessed means of encoding/decoding.

**Comment by natefaubion** [comment]
Or to put it another way, I'd like to see Argonaut implemented in terms of the functionality `Foreign` provides.

**Comment by paf31** [comment]
I'm not suggesting `Foreign` should provide a blessed means of encoding/decoding, but something like `foreign-generic` could, for example, and it would be built out of the functions in this library, like the ones I listed above. I do think we should move `IsForeign` and `AsForeign` out of this library though.

**Comment by natefaubion** [comment]
If you remove `IsForeign` and `AsForeign`, then the `foreign` in `foreign-generic` is just an implementation detail. Why tie it to the raw `Foreign` type and not just use a `newtype` instead for dispatching some typeclasses? You can even enforce only certain values are provided as appropriate. You've just invented Argonaut, in that case. It doesn't make sense to use the raw `Foreign` type for codecs because what if I want to encode using raw bytes or msgpack instead of JSON values? `Foreign` is all encompassing and doesn't signal to the user what your codec actually is, does, or guarantees. If you have a codec for JSON, the types should reflect that, likewise for any other medium.

**Comment by berdario** [comment]
I'm currently stuck on Purescript 0.10 due to some transitive dependencies, and I accept the fact that I'll rewrite a bunch of my code for Purescript 0.11 (and I'll try to contribute to argonaut-generics)... but I recently realized something that doesn't vibe well with the notion that:

> A PS program must run as JS, so all PS data is JS data

basically, `unsafeFromForeign <<< toForeign` should be `id` (and it is, after all the implementation is trivial)

but if marshalling PS values to JS (non-JSON) values is not supposed to be done explicitly (since we would have to write serializers and parsers, and at that point the effort would be better spent by generating proper JSON... this is my understanding), then I guess that we should be able to at least rely on `Foreign` as an opaque value

That is, either I think we/you've gone too far, and we shouldn't have removed `writeProp`, or I think that we haven't gone far enough, and we should remove `parseJSON`, or [change the way we represent and dispatch over sum types](https://github.com/purescript/purescript/issues/2577), since I'd expect that the following property should also hold:

```
roundTrips :: forall a. a -> Boolean
roundTrips a =
   isRight $ runExcept ((map unsafeFromForeign $ parseJSON $ unsafeStringify $ toForeign $ a) :: F a)
```

which holds for simple types, but not for sum types which require a tag (which is currently the constructor fn, which means that `JSON.parse` won't correctly set it, even if the stringified object is otherwise exactly the same).

**Comment by garyb** [comment]
Closing this as the classes are gone now, and `toForeign` has been renamed to `unsafeToForeign` with a warning about its intended usages.
