### ISSUE TITLE
Should `F` be `ExceptT MultipleErrors (Eff (foreign :: FOREIGN | eff)) a`?

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript-foreign#69]
Considering many foreign properties are mutable or can have arbitrary side-effects through getters. Or maybe `Foreign` should be considered "unsafe" in general?

**Comment by kl0tl** [comment]
This would be addressed by https://github.com/purescript/purescript-foreign/pull/74, right?

**Comment by hdgarrood** [comment]
I think that in practice Foreign is mostly used for parsing JSON, in which case there's no need to add effects and so this would be a rather awkward breaking change if we were switch the definition of `F` to be built on top of `Effect` rather than `Identity`. However, adding the transformer seems like a good way to allow people to opt in to having the stack be built on top of `Effect` rather than `Identity`, so I think we can consider it fixed by #74. I also think that if properties are mutable or have arbitrary side-effects, then it's probably more the user's responsibility to give them the appropriate types while reading them from Foreign.
